### ISSUE TITLE
Support for private messages

### ISSUE THREAD

**Issue by CarlosRodriguez1982** [a5mith/nodebb-plugin-import-smf#5]
I don't know if it misses other features to have full importer support, but it would be nice to have PM between them.

Regards.

**Comment by akhoury** [comment]
I will take a look while adding the messages. 
this issue's gonna have to wait for this first: https://github.com/akhoury/nodebb-plugin-import/pull/177

I'm gonna be out of town for the next 2 weeks, probably gonna have to wait till i get back.

**Comment by CarlosRodriguez1982** [comment]
Do you have some time to do it or I better try another importer like the phpbb one?

Regards.

**Comment by akhoury** [comment]
is your original forum SMF? it should be easy to add here. can you provide a database dump?

**Comment by CarlosRodriguez1982** [comment]
Today I was trying to import from SMF to vBulletin as it has already PM support, but it failed. Anyways I prefer to use the nodeBB importer, it is more straightforward and faster.

As GitHub does not let me attach the sql extension, I saved as txt the SMF 2.0 SQL structure:
[smf2.txt](https://github.com/a5mith/nodebb-plugin-import-smf/files/514425/smf2.txt)

Regards.

**Comment by colin-marshall** [comment]
@akhoury any progress on this? I can provide a dump if you need.

**Comment by akhoury** [comment]
@colin-marshall sorry for the late reply on this

i just pushed a major revamp to this, added support for attachments, groups, banned users, locked/pinned topics, few other stuff, but can't find the private messages table, that's the schema that i have, but the `smf_messages` is just the posts, not actual private messages.

![screen shot 2018-03-10 at 6 41 40 pm](https://user-images.githubusercontent.com/1398375/37244507-bb3d5cbe-2492-11e8-90ae-562d02de526c.png)

**Comment by akhoury** [comment]
actually never mind, i found them, im an idiot sometimes, they're in `smf_personal_messages` ill have this done by tomorrow
