### ISSUE TITLE
Error: ER_BAD_FIELD_ERROR: Unknown column 'smf_boards.lastUpdated' in 'field list'

### ISSUE THREAD

**Issue by AxelTerizaki** [a5mith/nodebb-plugin-import-smf#7]
The import starts well, but fails early when importing categories

There is obviously no such field in the smf_boards table.

I'm trying to import a SMF 2.0.12 forum

Could you help me out please?

**Comment by akhoury** [comment]
can you share a database dump?

**Comment by AxelTerizaki** [comment]
I'll send you a database dump at your mail. Tell me when you receive it.

**Comment by AxelTerizaki** [comment]
Just wanted to say thanks for fixing it :) It all worked great.

**Comment by akhoury** [comment]
glad I could help
